"""empty message

Revision ID: df2c763a4a38
Revises: 7dd83e7373b8
Create Date: 2022-03-22 13:04:55.674460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2c763a4a38'
down_revision = '7dd83e7373b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('bedrooms', sa.String(length=80), nullable=True),
    sa.Column('bathrooms', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('price', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('PropertyForm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PropertyForm',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"PropertyForm_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('bedrooms', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('bathrooms', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PropertyForm_pkey')
    )
    op.drop_table('Property')
    # ### end Alembic commands ###
